language: node_js
node_js:
  - lts/*
sudo: enabled
addons:
  ssh_known_hosts: 146.185.133.5
env:
  global:
  - REMOTE_APP_DIR=/usr/share/html/free-pooch/
  - REMOTE_USER=centos
  - REMOTE_HOST=146.185.133.5 # your droplet IP goes here
  - PORT=8080
before_install:
- openssl aes-256-cbc -K $encrypted_ad9b0644fe61_key -iv $encrypted_ad9b0644fe61_iv -in travis_ssh_key.enc -out travis_ssh_key -d
- bash deploy/install.sh
script:
- bash deploy/build.sh
- bash deploy/test.sh
after_success:
- bash deploy/deploy.sh
cache:
  directories:
  - client/node_modules
  - server/node_modules
  yarn: true
